### ISSUE TITLE
Error in vscode: "`gcc.exe' failed in phase `C pre-processor'. (Exit code: 1)"

### ISSUE THREAD

**Issue by jneira** [mpickering/haskell-ide-engine#47] opened 2019-11-14 00:33 UTC
* Opening `haskell-ide-engine/install` folder with the lastest hie-bios branch
* The error is shown as a editor alert at initialization and in each file saving
* hie doesnt respond at hover, etc
* hie handles the project correctly in master
* logs: https://gist.github.com/jneira/7cba45d34cb818f5c42b0a971444668f
```
GhcException on cradle initialisation: "`gcc.exe' failed in phase `C pre-processor'. (Exit code: 1)"
```
*  ~~The posible fix could involve handle that exception in `runActionWithContext` (thanks for point it out @mpickering)~~

**Comment by fendor** [comment] 2019-11-18 18:39
To add more context to this issue and how to reproduce it:
@jneira found that it happens on our install script project when you have *never* built it before.

Steps to reproduce:

```bash
git clone https://github.com/mpickering/haskell-ide-engine hie
cd hie/install
code .
```

or, if project is already cloned 
```bash
cd <path-to-haskell-ide-engine>/install
rm -rf .stack-work/ dist-newstyle/ dist/
code .
```
where `code .` is just an arbitrary lsp-client.

In the project `hie-install`, the cradle `Cabal-Helper-v2` will be selected due to the presence of `cabal.project`.
Simply opening any haskell source file in the project will lead to the described error message.
Error is specifically that a `cabal_macros.h` can not be found, which is not generated when c-h initialises the project context.
Workaround: use `stack build` and `cabal build` respectively to generate this file.

EDIT: adding a `hie.yaml` works for me as expected even when the project has never been built before.

**Comment by lukel97** [comment] 2019-11-18 20:29
[My own logs that run into this](https://gist.github.com/bubba/c98a5455c2766d2a66eb2622b76cf296)

**Comment by jneira** [comment] 2019-11-18 20:45
Thanks for summarize the bug @fendor.

**Comment by fendor** [comment] 2019-11-18 20:52
What @bubba is observing may or may not be a different issue :(

**Comment by jneira** [comment] 2019-11-19 10:26
> adding a hie.yaml works for me as expected even when the project has never been built before.

i think it is caused by using `hie.yaml`'s which triggers a `cabal repl` or `stack repl` and those commands generate the `cabal_macros.h` file. That observation could help us to fix the issue.

> What @bubba is observing may or may not be a different issue :(

To check it we should execute the ghc command with the args shown in the [log](https://gist.github.com/bubba/c98a5455c2766d2a66eb2622b76cf296#file-gistfile1-txt-L33), after deleting `dist-newstyle` and call `cabal v2-build --dry-run`.

**Comment by jneira** [comment] 2019-11-25 12:56
* There is an open issue in cabal about: https://github.com/haskell/cabal/issues/2209
* In short: it seems `cabal_macros.h` should be generated with `cabal v2-configure`or `cabal v2-build --only-configure` but it is not

**Comment by fendor** [comment] 2019-12-29 18:07
Closed in favour of https://github.com/haskell/haskell-ide-engine/issues/1519

**Closed as completed by fendor** 2019-12-29 18:07 UTC
